services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    container_name: "backend"
    hostname: "backend"
    network_mode: host
    env_file:
      - ./backend/.env

  audio:
    build:
      context: ./services/audio-service/
      dockerfile: Dockerfile
    restart: always
    container_name: "audio-service"
    hostname: "audio-service"
    network_mode: host
    env_file:
      - ./services/audio-service/.env
    volumes:
      - ./services/audio-service/data:/app/data/audio
