spring:
  application:
    name: svt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/svt
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USERNAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600